language: python
sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download
python:
  - "3.6"
before_install:
  - pip install pip -U
  - pip install pytest -U
  - pip install pytest-cov -U
  - pip install codecov -U
  - pip install xdoctest -U
  - pip install pygments -U
install:
  - travis_retry pip install -e .
script: 
  - travis_wait python run_tests.py
after_success: 
  - codecov 
#after_failure: 
#  - cat failed_doctests.txt
cache: 
    apt: true
    directories:
        - $HOME/.pip-cache
